python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_
python3 main.py -ng --name Gorynych_v1.4_