python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_
python3 main.py -ng --name Gorynych_v1.4.2_